"""doctor registration support

Revision ID: af6f02011633
Revises: 431f55ec8318
Create Date: 2026-08-02 15:57:36.421870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af6f02011633'
down_revision: Union[str, None] = '431f55ec8318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='doctorstatus'), nullable=True))
    op.add_column('doctors', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'doctors', ['user_id'])
    op.create_foreign_key(None, 'doctors', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.drop_constraint(None, 'doctors', type_='unique')
    op.drop_column('doctors', 'user_id')
    op.drop_column('doctors', 'status')
    # ### end Alembic commands ###
