"""create appointments table

Revision ID: b9aba1b8e506
Revises: cd1e7ea8a34f
Create Date: 2026-08-01 18:59:15.222184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9aba1b8e506'
down_revision: Union[str, None] = 'cd1e7ea8a34f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
