"""replace first and last name with full_name in  patients table

Revision ID: c512d95cc667
Revises: 7553340da502
Create Date: 2026-07-28 09:58:34.241161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c512d95cc667'
down_revision: Union[str, None] = '7553340da502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('full_name', sa.String(length=100), nullable=False))
    op.drop_column('patients', 'first_name')
    op.drop_column('patients', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('patients', 'full_name')
    # ### end Alembic commands ###
