"""update doctor schema

Revision ID: cd1e7ea8a34f
Revises: 09d5eb45a42c
Create Date: 2026-08-01 17:01:36.305209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd1e7ea8a34f'
down_revision: Union[str, None] = '09d5eb45a42c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('specialization', sa.Enum('CARDIOLOGY', 'DERMATOLOGY', 'NEUROLOGY', 'PEDIATRICS', 'ORTHOPEDICS', 'GYNECOLOGY', 'PSYCHIATRY', 'ONCOLOGY', 'RADIOLOGY', 'UROLOGY', 'GASTROENTEROLOGY', 'GENERAL_PHYSICIAN', name='specialization'), nullable=False),
    sa.Column('department', sa.Enum('MEDICINE', 'SURGERY', 'EMERGENCY', 'ICU', 'ENT', 'OPD', 'RADIOLOGY', 'ORTHOPEDICS', name='department'), nullable=False),
    sa.Column('qualification', sa.String(length=150), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('consultation_fee', sa.Float(), nullable=False),
    sa.Column('availability', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_doctors_doctor_id'), 'doctors', ['doctor_id'], unique=True)
    op.create_index(op.f('ix_doctors_id'), 'doctors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctors_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_doctor_id'), table_name='doctors')
    op.drop_table('doctors')
    # ### end Alembic commands ###
